timer: 300  # Intervall in Sekunden
ip_service: "https://api.ipify.org"
ip6_service: "https://api64.ipify.org"
providers:
  - name: duckdns
    protocol: dyndns2
    url: "https://www.duckdns.org/update"
    token: "your-duckdns-token"
    domain: "example"

  - name: noip-home
    protocol: dyndns2
    url: "https://dynupdate.no-ip.com/nic/update"
    username: "your-noip-username"
    password: "your-noip-password"
    hostname: "example.ddns.net"

  - name: mein-cloudflare
    protocol: cloudflare
    zone: "deinedomain.tld"
    api_token: "dein_cloudflare_api_token"
    record_name: "sub.domain.tld"

  - name: mein-ipv64
    protocol: ipv64
    url: "https://ipv64.net/nic/update"
    auth_method: "token"
    token: "dein_update_token"
    domain: "deinedomain.ipv64.net"

  - name: dynu
    protocol: dyndns2
    url: "https://api.dynu.com/nic/update"
    auth_method: "basic"
    username: "deinuser"
    password: "deinpass"
    hostname: "deinedomain.dynu.net"

