# Beispiel-Konfiguration für DynDNS Docker Client
# Kopiere diese Datei zu config/config.yaml und passe sie an deine Bedürfnisse an!

# Intervall in Sekunden für die IP-Prüfung (z.B. alle 5 Minuten)
timer: 300

# Service zum Abrufen der öffentlichen IPv4-Adresse
ip_service: "https://api.ipify.org"

# Service zum Abrufen der öffentlichen IPv6-Adresse (optional)
# ip6_service: "https://api64.ipify.org"

# Liste der zu aktualisierenden Provider
providers: 
# ACHTUNG: Dieses Feld darf NICHT entfernt oder auskommentiert werden!
# Trage hier deine Provider ein, siehe Beispiele unten.

#   - name: duckdns
#     protocol: dyndns2
#     url: "https://www.duckdns.org/update"
#     token: "your-duckdns-token"
#     domain: "example"  # DuckDNS erwartet 'domain'

#   - name: noip-home
#     protocol: dyndns2
#     url: "https://dynupdate.no-ip.com/nic/update"
#     username: "your-noip-username"
#     password: "your-noip-password"
#     hostname: "example.ddns.net"  # NoIP erwartet 'hostname'

#   - name: dynu
#     protocol: dyndns2
#     url: "https://api.dynu.com/nic/update"
#     auth_method: "basic"
#     username: "deinuser"
#     password: "deinpass"
#     hostname: "deinedomain.dynu.net"  # Dynu erwartet 'hostname'

#   - name: mein-cloudflare
#     protocol: cloudflare
#     zone: "deinedomain.tld"
#     api_token: "dein_cloudflare_api_token"
#     record_name: "sub.domain.tld"

#   - name: mein-ipv64
#     protocol: ipv64
#     # url ist NICHT nötig für ipv64, wird im Code fest gesetzt!
#     auth_method: "token"  # oder "basic" oder "bearer"
#     token: "dein_update_token"
#     domain: "deinedomain.ipv64.net"

#   - name: beispiel-bearer
#     protocol: dyndns2
#     url: "https://example.com/nic/update"
#     auth_method: "bearer"
#     token: "dein_bearer_token"
#     hostname: "deinhost.example.com"

#   - name: beispiel-mit-host
#     protocol: dyndns2
#     url: "https://example.com/nic/update"
#     token: "dein_token"
#     host: "deinhost.example.com"

# Hinweise:
# - Für dyndns2-Provider ist das Feld 'url' Pflicht!
# - Für cloudflare und ipv64 ist die URL im Code fest hinterlegt.
# - Je nach Provider werden die Felder 'domain', 'hostname' oder 'host' benötigt.
# - auth_method kann "token", "basic" oder "bearer" sein (je nach Provider/API).