timer: 300  # Intervall in Sekunden
ip_service: "https://api.ipify.org"
providers:
  - name: duckdns # DuckDNS provider
    url: "https://www.duckdns.org/update" # URL for DuckDNS update
    params:
      domains: "example" # Your DuckDNS subdomain
      token: "your-duckdns-token" # Your DuckDNS token

  - name: noip
    url: "https://dynupdate.no-ip.com/nic/update"
    params:
      hostname: "example.ddns.net" # Your No-IP hostname
      username: "your-noip-username" # Your No-IP username
      password: "your-noip-password" # Your No-IP password

  - name: cloudflare
    zone: "deinedomain.tld"
    api_token: "dein_cloudflare_api_token"
    record_name: "sub.domain.tld"

  - name: ipv64
    url: "https://ipv64.net/nic/update"
    auth_method: "token"  # "token", "basic", "bearer"
    token: "dein_update_token"
    domain: "deinedomain.ipv64.net"

  - name: custom-dyndns2
    url: "https://example.com/nic/update"
    protocol: "dyndns2"
    auth_method: "token"  # oder "basic", "bearer"
    token: "dein_update_token"
    domain: "deinedomain.example.com"